//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class Chapters {
    
    private EditionEntry[] editionEntryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EditionEntry")]
    public EditionEntry[] EditionEntry {
        get {
            return this.editionEntryField;
        }
        set {
            this.editionEntryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class EditionEntry {
    
    private string editionUIDField;
    
    private string editionFlagHiddenField;
    
    private string editionManagedField;
    
    private string editionFlagDefaultField;
    
    private ChapterAtom[] chapterAtomField;
    
    /// <remarks/>
    public string EditionUID {
        get {
            return this.editionUIDField;
        }
        set {
            this.editionUIDField = value;
        }
    }
    
    /// <remarks/>
    public string EditionFlagHidden {
        get {
            return this.editionFlagHiddenField;
        }
        set {
            this.editionFlagHiddenField = value;
        }
    }
    
    /// <remarks/>
    public string EditionManaged {
        get {
            return this.editionManagedField;
        }
        set {
            this.editionManagedField = value;
        }
    }
    
    /// <remarks/>
    public string EditionFlagDefault {
        get {
            return this.editionFlagDefaultField;
        }
        set {
            this.editionFlagDefaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterAtom")]
    public ChapterAtom[] ChapterAtom {
        get {
            return this.chapterAtomField;
        }
        set {
            this.chapterAtomField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class ChapterAtom {
    
    private string chapterTimeStartField;
    
    private string chapterTimeEndField;
    
    private string chapterUIDField;
    
    private string chapterSegmentUIDField;
    
    private string chapterSegmentEditionUIDField;
    
    private string chapterPhysicalEquivField;
    
    private ChapterTrack chapterTrackField;
    
    private string chapterFlagHiddenField;
    
    private string chapterFlagEnabledField;
    
    private ChapterDisplay[] chapterDisplayField;
    
    private ChapterProcess[] chapterProcessField;
    
    private ChapterAtom[] chapterAtom1Field;
    
    /// <remarks/>
    public string ChapterTimeStart {
        get {
            return this.chapterTimeStartField;
        }
        set {
            this.chapterTimeStartField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterTimeEnd {
        get {
            return this.chapterTimeEndField;
        }
        set {
            this.chapterTimeEndField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterUID {
        get {
            return this.chapterUIDField;
        }
        set {
            this.chapterUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterSegmentUID {
        get {
            return this.chapterSegmentUIDField;
        }
        set {
            this.chapterSegmentUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterSegmentEditionUID {
        get {
            return this.chapterSegmentEditionUIDField;
        }
        set {
            this.chapterSegmentEditionUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterPhysicalEquiv {
        get {
            return this.chapterPhysicalEquivField;
        }
        set {
            this.chapterPhysicalEquivField = value;
        }
    }
    
    /// <remarks/>
    public ChapterTrack ChapterTrack {
        get {
            return this.chapterTrackField;
        }
        set {
            this.chapterTrackField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterFlagHidden {
        get {
            return this.chapterFlagHiddenField;
        }
        set {
            this.chapterFlagHiddenField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterFlagEnabled {
        get {
            return this.chapterFlagEnabledField;
        }
        set {
            this.chapterFlagEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterDisplay")]
    public ChapterDisplay[] ChapterDisplay {
        get {
            return this.chapterDisplayField;
        }
        set {
            this.chapterDisplayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterProcess")]
    public ChapterProcess[] ChapterProcess {
        get {
            return this.chapterProcessField;
        }
        set {
            this.chapterProcessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterAtom")]
    public ChapterAtom[] ChapterAtom1 {
        get {
            return this.chapterAtom1Field;
        }
        set {
            this.chapterAtom1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class ChapterTrack {
    
    private string chapterTrackNumberField;
    
    /// <remarks/>
    public string ChapterTrackNumber {
        get {
            return this.chapterTrackNumberField;
        }
        set {
            this.chapterTrackNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class ChapterDisplay {
    
    private string chapterStringField;
    
    private string[] chapterLanguageField;
    
    private string[] chapterCountryField;
    
    /// <remarks/>
    public string ChapterString {
        get {
            return this.chapterStringField;
        }
        set {
            this.chapterStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterLanguage")]
    public string[] ChapterLanguage {
        get {
            return this.chapterLanguageField;
        }
        set {
            this.chapterLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterCountry")]
    public string[] ChapterCountry {
        get {
            return this.chapterCountryField;
        }
        set {
            this.chapterCountryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class ChapterProcess {
    
    private string chapterProcessCodecIDField;
    
    private string chapterProcessPrivateField;
    
    private ChapterProcessCommand[] chapterProcessCommandField;
    
    /// <remarks/>
    public string ChapterProcessCodecID {
        get {
            return this.chapterProcessCodecIDField;
        }
        set {
            this.chapterProcessCodecIDField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterProcessPrivate {
        get {
            return this.chapterProcessPrivateField;
        }
        set {
            this.chapterProcessPrivateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChapterProcessCommand")]
    public ChapterProcessCommand[] ChapterProcessCommand {
        get {
            return this.chapterProcessCommandField;
        }
        set {
            this.chapterProcessCommandField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
public partial class ChapterProcessCommand {
    
    private string chapterProcessTimeField;
    
    private string chapterProcessDataField;
    
    /// <remarks/>
    public string ChapterProcessTime {
        get {
            return this.chapterProcessTimeField;
        }
        set {
            this.chapterProcessTimeField = value;
        }
    }
    
    /// <remarks/>
    public string ChapterProcessData {
        get {
            return this.chapterProcessDataField;
        }
        set {
            this.chapterProcessDataField = value;
        }
    }
}
